# DEFINITENESS QUESTIONS:
MAX_DIM = 3
MAX_EIGENVALUE_MOD = 2
MAX_EIGENVECTOR_COMP_MOD = 3

# STATIONARY POINTS QUETIONS:
MAX_NUM_OF_TERMS = 5
MIN_NUM_OF_TERMS = 3
MAX_FUNC_DIM = 3
MAX_POWER = 2

# EQUALITY CONSTRAINTS QUESTIONS:
MAX_NUM_OF_VARS = 3
MAX_NUM_OF_TERMS_EQ = 4
MIN_NUM_OF_TERMS_EQ = 3